package com.whoami.businessoperation.domain.enums;

public enum AuditAction {

    BUSINESS_CREATED,
    APPLICATION_CREATED,
    APPLICATION_SUBMITTED,

    DOCUMENT_UPLOADED,
    DOCUMENT_UPDATED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,

    VERIFICATION_STARTED,
    VERIFICATION_SUBMITTED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    REUPLOAD_REQUESTED,

    BUSINESS_APPROVED,
    BUSINESS_REJECTED,

    BUSINESS_ACTIVATED,
    BUSINESS_DEACTIVATED,

    CAPABILITY_ENABLED,
    CAPABILITY_DISABLED,

    BUSINESS_SUSPENDED,
    BUSINESS_REACTIVATED,

    BUSINESS_CLOSED,

    ADMIN_ACTION,
    SYSTEM_ACTION
}