package com.locato.constants.events;

public enum BusinessEventType {

    BUSINESS_CREATED,

    APPLICATION_CREATED,
    APPLICATION_SUBMITTED,

    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_REUPLOAD_REQUIRED,

    VERIFICATION_STARTED,
    VERIFICATION_SUBMITTED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    VERIFICATION_REUPLOAD_REQUIRED,

    BUSINESS_APPROVED,
    BUSINESS_REJECTED,

    BUSINESS_ACTIVATED,
    BUSINESS_DEACTIVATED,
    BUSINESS_SUSPENDED,
    BUSINESS_REACTIVATED,
    BUSINESS_CLOSED,

    CAPABILITY_ENABLED,
    CAPABILITY_DISABLED,
    CAPABILITY_SUSPENDED
}