CREATE DATABASE IF NOT EXISTS user;

CREATE DATABASE IF NOT EXISTS shop;

CREATE DATABASE IF NOT EXISTS messageuser;

CREATE DATABASE IF NOT EXISTS `order`;

CREATE DATABASE IF NOT EXISTS notification;

CREATE DATABASE IF NOT EXISTS superuser;