name: Reusable Build

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

      image-name:
        required: true
        type: string

      gitops-service:
        required: true
        type: string

      dockerfile:
        required: true
        type: string

      image-tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Service
        uses: ./.github/actions/build-service
        with:
          module: ${{ inputs.module }}
          dockerfile: ${{ inputs.dockerfile }}
          image-name: ${{ inputs.image-name }}
          image-tag: ${{ inputs.image-tag }}
          firebase-credentials: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Notify GitOps Repository
        uses: ./.github/actions/notify-gitops
        with:
          service: ${{ inputs.gitops-service }}
          image: ${{ inputs.image-name }}
          tag: ${{ inputs.image-tag }}
          environment: development
