spring.application.name=BillingService

server.port=8089

# ===============================

# MySQL

# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/dhondoo_billing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

spring.datasource.username=${DB_USERNAME:root}

spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================

# JPA / Hibernate

# ===============================

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================

# Kafka

# ===============================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:billing-service}

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.enable-auto-commit=false

# Kafka Consumer Error Handling

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.locato.dto.billing.event

spring.kafka.consumer.properties.spring.json.value.default.type=com.locato.dto.billing.event.BillingRequestedEvent

# Kafka Producer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===============================

# Logging

# ===============================

logging.level.com.whoami.billing=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.hibernate.SQL=DEBUG

# ===============================

# Actuator

# ===============================

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=when_authorized

management.prometheus.metrics.export.enabled=true

#=======


#  for schedule runnig
#======

billing.recurring.cron=0 0 2 * * *


billing.recurring.timezone=Asia/Kolkata